export var videos = [
  {
    poster:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Classic_2.png",
    video:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Classic_2_v2.mp4",
  },
  {
    poster:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Underline_bar.png",
    video:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Underline_bar_v2.mp4",
  },
  {
    poster:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Sleek_2b_v3.png",
    video:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Sleek_2b_v3.mp4",
  },
  {
    poster:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Smart_2b.png",
    video:
      "https://storage.googleapis.com/lumen5-site-images/Prev_Smart_2b_v2.mp4",
  },
];
